### ISSUE TITLE
Peripheral pins defined in BoardConfig.h are not getting ASSIGNED_TO_ADDON on a fresh board

### ISSUE THREAD

**Issue by jakubkoziol** [OpenStickCommunity/GP2040-CE#778]
### Prerequisites

Please check the following before posting an issue / bug report.

- [x] I am running the latest version of the firmware found [HERE](https://github.com/OpenStickCommunity/GP2040-CE/releases)
- [x] I have checked the documentation [HERE](https://gp2040-ce.info/) and found no answer
- [x] I checked to make sure that this issue has not already been filed [HERE](https://github.com/OpenStickCommunity/GP2040-CE/issues)
- [x] I am reporting the issue to the correct repository

### Context

* Firmware Version: 0.7.6
* Name of device: any
* Link to where you purchased the device: n/a
* Is this a custom build?: no
* Operating System: n/a
* Browser: n/a

### Expected Behavior

"Peripheral Mapping" pins defined in BoardConfig.h can't be used in the "Pin Mapping" screen using the Web Config.

### Current Behavior

On a freshly flashed board with a display and/or a USB Host defined in the BoardConfig.h those pins are not blocked in the "Pin Mapping" screen and can be assigned to a button.
Saving on the "Peripheral Mapping" screen returns to the expected behavior.

### Steps to Reproduce

1. Nuke-flash a board using firmware with display and/or USB Host defined in the BoardConfig (for example RP2040ABB or Haute42).
2. Go to "Pin Mapping" in the Web Configurator.
3. Observe that pins assigned to the display or USB Host in BoardConfig.h are not blocked.
4. Go to "Peripheral Mapping".
5. Click "Save".
6. Go back to the "Pin Mapping" screen.
7. Observe that pins are properly displayed as "Assigned to addon".

**Comment by TheTrainGoes** [comment]
Hi @jakubkoziol ,

This has already been addressed and is fixed in main.  You will need to either compile from there or wait for our v0.7.7 release which should be coming soon.

**Comment by jakubkoziol** [comment]
@TheTrainGoes 

Compiled as of commit bcf73abc44cc4a573934e23750d2a2bc47f2e7fa I'm still seeing this behavior.
